### ISSUE TITLE
Logger cannot write, stopping action completion

### ISSUE THREAD

**Issue by samnissen** [watir/watir#667]
## Meta -
Watir Version: 6.2
Selenium Version: 3.3 
Browser Version: 52.0
Browser Driver Version: 0.18
OS Version: CentOS 7.2

## Expected Behavior -
Legacy wait would work as otherwise expected regardless of logging intention or result

## Actual Behavior -
Legacy wait fails if logging permission is not present

## Steps to reproduce -
Running a daemonized process, my app in effect executes
```ruby
b = Watir::Browser.new
b.goto "https://google.com"
b.text_field(:id => "lst-ib").when_present.set("something")
Errno::EIO - Input/output error @ io_write - <STDERR>
    from /user/path/.rvm/gems/ruby-2.3.0/gems/watir-6.2.0/lib/watir/legacy_wait.rb:86:in `write'
    from /user/path/.rvm/gems/ruby-2.3.0/gems/watir-6.2.0/lib/watir/legacy_wait.rb:86:in `warn'
    from /user/path/.rvm/gems/ruby-2.3.0/gems/watir-6.2.0/lib/watir/legacy_wait.rb:86:in `when_present'
    # ... in the app, this is followed by bunch of app logs
```

**Comment by titusfortner** [comment]
If your process can not write to STDOUT, change where the log information is getting sent:

```ruby
Watir.logger.output = 'watir.log'
```

**Comment by samnissen** [comment]
FYI this doesn't work in 6.2, because it's `warn`, not logger, sending this to STDOUT.

```ruby
$ irb
2.4.0 :001 > require 'watir'
 => true
2.4.0 :002 > Watir.logger.output = "/dev/null"
NoMethodError: undefined method `logger' for Watir:Module
	from (irb):2
	from /Users/samuel.nissen/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'
2.4.0 :003 > puts Gem.loaded_specs["watir"].version
6.2.1
 => nil
```

**Comment by titusfortner** [comment]
Ah, yes, update to 6.6+ :)
