### ISSUE TITLE
“invalid argument: 'name' must be a string” when trying to set Edge driver on Watir

### ISSUE THREAD

**Issue by alex-b3** [watir/watir#897]
## Meta -
Watir Version: 6.14.0
Selenium Version: 
Browser Version: edge 85.0.564.44
Browser Driver Version: edge 85.0.564.44
OS Version: mac

I am trying to add edge driver to our automation tests suite. I am setting the driver like that:

Selenium::WebDriver::Edge::Service.driver_path = EDGEDRIVER_PATH
    Watir::Browser.new BROWSER.to_sym,{:unexpected_alert_behaviour => 'ignore',  "edgeOptions" => {'w3c' => false, :args => args} }

When I am trying to maximize window size with @browser.window.maximize I am getting this error:

invalid argument: 'name' must be a string
  (Session info: MicrosoftEdge=85.0.564.44)
  (Driver info: msedgedriver=85.0.564.44 (3b106b45f8e7cd4c3e2aac5a6ba411645c16df60),platform=Mac OS X 10.14.6 x86_64)

Thanks.

**Comment by TheSpartan1980** [comment]
@alex-b3 You can use the following to workaround this issue
```ruby
Selenium::WebDriver::Edge::Service.driver_path = edgedriver_path
@browser = Watir::Browser.new :edge, {:unexpected_alert_behaviour => 'ignore', "edgeOptions" => {'w3c' => false, :args => ['start-maximized']} }
```

I encounter the same issue as you when using any of the following:
```ruby
@browser.window.maximize
@browser.window.size
@browser.window.resize_to(1920, 1080)
```

**Comment by alex-b3** [comment]
> @alex-b3 You can use the following to workaround this issue
> 
> ```ruby
> Selenium::WebDriver::Edge::Service.driver_path = edgedriver_path
> @browser = Watir::Browser.new :edge, {:unexpected_alert_behaviour => 'ignore', "edgeOptions" => {'w3c' => false, :args => ['start-maximized']} }
> ```
> 
> I encounter the same issue as you when using any of the following:
> 
> ```ruby
> @browser.window.maximize
> @browser.window.size
> @browser.window.resize_to(1920, 1080)
> ```

Thanks for reply, I found another workaround: @browser.driver.manage.window.maximize

but the issue does not ends here, I am getting errors on page object commands, for example:

on the line: self.password = 'a'

I am getting:
Selenium::WebDriver::Error::JavascriptError: javascript error: a.getAttributeNode is not a function
  (Session info: MicrosoftEdge=85.0.564.63)
  (Driver info: msedgedriver=85.0.564.51 (626274a16bb350129a74ead7a3d8d53a5ad39364),platform=Mac OS X 10.14.6 x86_64)
(eval):1:in `process_watir_call'


thanks in advance

**Comment by titusfortner** [comment]
Watir 6 & Selenium 3 do not actually support the Chromium version of Edge. The current Edge classes are only for legacy Edge HTML version.

Watir 7 will have support for it, but in the meantime you can probably make it work with Watir 6.18 and the Selenium 4 beta:
```ruby
driver = Selenium::WebDriver.for :edge, capabilities: Selenium::WebDriver::Edge::Options.new(opts)
browser = Watir::Browser.new(driver)
```
